현초은 [자동차 경주 게임] 제출합니다
croffle-lover/java-racingcar pull request #1
Opened 2023-07-17 05:51 UTC by 2384320

늘 드렸던 링크입니당
https://swift-badge-161.notion.site/53ad907c1bbe4eb4a8375b144bb3327b?pvs=4

데이터 나누는 (자동차 이름이 쉼표로 구분되어 있던걸 나누는) 일은 모델에서 하도록 했습니다.

1. 우선 다시 한번 뷰와 모델의 역할에 대해 생각해봤습니다.
뷰는 컨트롤러에서 받은 데이터를 출력하고, 클라이언트에 의해 입력받은 값을 컨트롤러로 전달하는 역할 외에는 뷰와는 맞지 않다고 생각했습니다.
모델의 경우는 MVC 모델 기준 데이터를 처리하는 역할을 하고 있기 때문에 데이터를 나누는 일도 모델이 맡아야 한다고 생각했습니다.
2. 강의로 배웠던 TDD 관점으로 생각해봤습니다.
모든 기능을 테스트할 순 없겠지만 - EX) 출력과 관련된 테스트 (이번에는 모델에 관련된 테스트만 작성했습니다.)
클라이언트의 입력과 관련된 중요한 부분은 꼭 테스트가 필요하다고 생각했습니다.
그래서 모델로 옮겨 테스트와 함께 구현했습니다.

그래서 MVC 자체에서는 데이터를 나누는 역할은 모델이 맡아야 한다고 생각합니다.

다만 MVC 모델에서 벗어나서 다른 모델을 사용한다면 그때는 모델이 아닌 다른 친구가 이 역할을 사용해야 할 것 같습니당.
MVC로 코드를 짜니깐 모델이 입력값에 따라 작성이 돼서 효율이 너무 떨어지는 느낌이 들었습니다.

2023-07-23 15:32 UTC, bandal-reviewer requested changes
자동차 경주 미션 고생하셨습니다! 정리하신 의견 잘 봤습니다.😀😀 

MVC 아키텍쳐 패턴도 그렇고 MVP, MVVM , MVI 여러가지의 아키텍쳐 패턴이 있지만, 모든 사람이 다 의견이 다릅니다. 
하지만 공통적으로 지켜져야할 사항은 있죠. 이 부분은 필수적으로 가져가되 사람들끼리 의견이 갈리는 부분에선 초은님이 **근거**를 가지고 초은님만의 의견을 가져갔음 좋겠습니다!

몇가지 코멘트 남겼으니 확인해주시고 다시 리뷰요청 주세요!

2023-07-23 15:32 UTC, croffle-lover commented on src/main/java/Domain/RandomNumber.java
> +}
`random.nextInt(10)`에 있는 10은 무엇을 의미하나요? 우리는 코드만 보고도 뜻을 이해할 수 있어야합니다.
그렇게 하려면 우린 어떻게 하기로 했었죠?ㅎㅎ

2023-07-23 15:32 UTC, croffle-lover commented on src/test/java/Domain/CarTest.java
> +    }
`자동차의 이름은 5자를 초과할 수없다.` 라는 이름의 테스트이지만 valueSource로 들어가는 인자중에 ""이 포함되어있네요? 
어색한 부분이 있다고 생각됩니다.
"" 은 5글자를 초과하지 않는데 왜 예외처리 될까요?
항상 해당 코드에 대해 아무것도 모르는 사람이 봐도 이해할 수 있는 코드를 만들어주세요!

2023-07-23 15:32 UTC, croffle-lover commented on src/main/java/Domain/Cars.java
> +    private static final String CLASSIFICATION_SYMBOL = ",";
훌륭한 상수화 좋습니다.
하지만 `separator`라는 더 좋은 이름이 있을 것 같네요!

2023-07-23 15:32 UTC, croffle-lover commented on src/test/java/Domain/CarsTest.java
> +}
`moveAll()`이라는 메서드의 테스트가 빠져있네요?
혹시 실수로 빠뜨리신거면 채워주시고 문제가 있어서 못했던 거라면 코멘트 또는 dm주셔도 좋습니다!

2023-07-23 15:32 UTC, bandal-reviewer commented on src/test/java/Domain/WinnerTest.java
> +    }
자동차들의 우승자를 테스트하는 과정에서
2번 3번 자동차들을 미리 움직여 놓는 **준비** 과정이 있네요 해당 사항은 when절에 어울리진 않아보입니다!

2023-07-23 15:32 UTC, bandal-reviewer commented on src/main/java/Domain/Cars.java
> +    }
내부에서만 사용하는 메서드는 항상 private로 은닉화를 해주세요!

2023-07-23 15:32 UTC, bandal-reviewer commented on src/test/java/Domain/WinnerTest.java
> +    }
요구사항엔 없던 내용이지만 지금의 경우 두 자동차가 전부 한 번도 못움직인 상태입니다. 
출발을 둘 다 안한 상황이라고 볼 수 있죠.
한 칸이라도 두 자동차 모두 가야 그 때 부터 공동우승의 의미가 있지 않을까요?

2023-07-23 15:32 UTC, bandal-reviewer commented on src/test/java/Domain/WinnerTest.java
> +    }
추가로 우승자가 한 명 이상일 수 있다라는 테스트인데 불구하고 현재 테스트는 공동우승일 경우만 테스트하고 있습니다. 항상 다양한 상황을 되도록이면 전부 고려해주세요.

2023-07-23 15:32 UTC, bandal-reviewer commented on src/test/java/Domain/WinnerTest.java
> +        Winner winner = new Winner(cars);
추가로 이런식으로 자동차들을 각각 움직이게 하는 방법도 있지만 더 좋은 방법으로 각 자동차들이 움직인 거리를 미리 세팅해줄 수 있습니다. 

**힌트: 부생성자**

2023-07-23 15:32 UTC, bandal-reviewer commented on src/main/java/Domain/Winner.java
> +}
우승자를 가려내는 클래스군요. 좋습니다😀😀
여러가지 방법이 있을 것 같은데 당장에 생각나는 방법은 다음과 같습니다. 
1. Winner 인스턴스를 생성한 뒤 우승자를 가려내는 메서드에 자동차들을 넣어 우승자들을 받아낸다.
2. Winner 클래스를 만들 때 바로 자동차이름을 넘겨주고 winner를 필드로 가지고 있게 한다.
3. Winner의 생성자를 막아두고 팩토리 메서드 패턴을 사용한다. 
4. Winner를 싱글턴으로 만들고 오직 우승자를 가려주는 역할만 하게끔 한다.

이처럼 수많은 방법이 있는데 초은님이 구성한 이 Winner에 대한 장단점과 왜 이 방법으로 구성했는지 이유를 코멘트로 달아주세요!

정답은 없습니다. 그저 초은님이 작성한 코드에 대한 의견을 듣고싶은 겁니다!

2023-07-24 08:26 UTC, 2384320 commented on src/main/java/Domain/RandomNumber.java
> +}
상수로 만들어서 처음보는 사람에게 이 값이 어떤 값을 의미하는지 알려줘야 해요

2023-07-24 12:04 UTC, 2384320 commented on src/main/java/Domain/Winner.java
> +}
원래는 n번의 횟수 동안 어떤 자동차가 얼마나 전진했는지를 다 기록한 후에 우승자와 결과 화면을 출력하려고 했습니다.
그래서 Winner 객체 대신에 Result 객체를 사용하려고 했어요.

Result에는 result Map을 통해 i회를 나타내는 key와 n회에 어떤 기록을 남겼는지에 대한 Cars를 남기려고 했어요.
그러다가 Cars 안에 Car 객체를 통째로 저장했더니 객체 안에 있는 데이터가 저장되는게 아니라 객체 자체가 저장돼서
i회에 대한 기록이 남는게 아니라 n회를 모두 마친 후의 기록이 남아서 기록을 남기는 건 포기했어요,

다음으로 작성한게 이 Winner 객체입니다.
i회에 대한 기록을 출력하는 건 한 횟수가 끝날 때마다 출력시키도록 했고,
Winner 객체에서는 모든 경주 점수가 집계된 자동차들 중에 가장 멀리 이동한 위치를 고르도록 했고,
멀리 이동한 위치에 어떤 자동차가 위치하는지를 고르는 메서드를 집어 넣어서 결과만을 저장하도록 했습니다.

제가 Winner를 만들면서 생각했던 건
1) Cars도 Car의 집합인 것처럼 Winner도 더 멀리나간 position에 해당하는 Car의 집합으로 해야겠다
2) Result가 아닌 Winner로 변경했으니 우승자에 대한 역할만 할 수 있도록 해야겠다
였습니다.

장점은 우승자를 선별하기 위한 역할에 집중한다는 점이 있을 것 같습니다.

단점은 Winner 객체를 붙들고 있기에는 정체성이 약하다는 점이 있을 것 같습니다.
우승자를 선별하여 반환하는 것은 Cars 객체에서도 충분히 이루어질 수 있지 않을까 싶습니다.
굳이 maxPosition과 winner를 저장할 필요없이 출력하고자 할 때 Cars 객체의 메소드를 활용해서 값을 구한 후에 반환할 수도 있기 때문입니다.

2023-07-24 12:12 UTC, 2384320 commented on src/test/java/Domain/CarsTest.java
> +}
moveAll()이 car.move()에 랜덤 값을 넣는 역할을 해서 어떻게 테스트를 작성해야 할지 모르겠어요

2023-07-26 12:46 UTC, bandal-reviewer requested changes
피드백 반영 고생 많으셨습니다!! 일단은 하나만 리뷰해드리도록 하겠습니다.
리뷰해드린 내용 하나만으로 충분히 생각하고 공부해볼만하다고 생각들어서 입니다.

**한 가지 더 부탁드리자면 TDD를 배우고 적용을 해보는 시간을 가졌는데 어떤걸 느끼셨고 어떤 장단점을 느끼셨는지 코멘트로 남겨주시면 좋을 듯합니다!**

2023-07-26 12:46 UTC, bandal-reviewer commented on src/main/java/Domain/Cars.java
> +    }
이 부분은 완전하게 랜덤 값에 대해 분리가 되질 않아 테스트가 어려우실듯 합니다.

이 `moveAll()`은 사실 cars의 모든 자동차로 하여금 move 함수를 호출했냐가 관심사고 테스트해야할 사항입니다.

그렇게 하려면 어떻게 해야할까요?

**랜덤 값을 제어해야합니다.**

초은님의 `RandomNumber`는 현재 interface를 구현하고 있지 않습니다. 

`moveAll()`의 매개변수로 `NumberGenerator`라는 인터페이스 구현체를 받도록 하고

`car.move(numberGenerator.generateNumber)`를 호출하도록 하면 어떨까요?

우리가 인터페이스를 왜쓰는지 한번 공부해보시면서 적용해보시면 좋을 것 같습니다!

당장 이해 되지 않더라도 나중에 이해하면 아 이게 이런 말이었구나 느끼실 겁니다!! 화이팅!

2023-07-27 12:18 UTC, 2384320 commented
장점
1. 처음에 말해주신 것처럼 이 친구가 방향을 잡아주니 하나의 기능 구현에 집중할 수 있었어요.
TDD 없이 구현했으면 이 기능 구현하다가 저 기능 생각나서 꼬이기 마련이었는데,
기능 리스트를 기반으로 진행되니 하나에만 집중할 수 있고 다른 기능과 섞일 생각을 안 해도 되니 좋았어요.
2. 지금 코드 상황이 어떤 상황이며 이 다음에는 뭘 해야 될지 한 눈에 정리돼서 좋았어요.
기능 중심으로 TDD가 움직이다 보니 이미 완성된 기능을 목록에서 지워가면서 할 수 있어서 집중적으로 할 수 있었어요.
3. 사이클이 안정적이었어요.
테스트를 작성할 수 있는 조건 하에 Red - Green - Blue의 개발 과정이 예외 없이 적용할 수 있어서 안정적으로 개발을 할 수 있었어요.

단점
1. 사용처가 한정적이었어요.
TDD 말 그대로 테스트 주도 개발이라서 테스트를 할 수 없는 부분에서는 사용할 수 없다는 점이 가장 큰 단점이지 않았나 싶었어요.
2. Green 단계의 필요성이 잘 안 느껴졌어요.
이번 미션에서 TDD를 하면서 특히 Red의 필요성은 확실히 이해했지만 Green 단계는 잘 이해하지 못했어요.
Red 단계를 작성하면서 어떻게 Blue에서 코드를 짜면 될 지 머리에서 계산이 잘 되는 부분에서는 Green이 오히려 방해됐어요.
어느 정도 개발이 되어있는 상황에서는 Green을 통과시키기 위해 전에 정상적으로 작동되던 코드를 수정하기도 하는 등 여러모로 정적인 답을 주는 과정이 오히려 어려웠어요.

TDD는 계획적으로 개발하기에 최적화되어 있어서 당장 뭐부터 손댈지 고민하는 사람이나 하나의 기능에 집중하지 못하는 사람에게는 좋을 것 같아요.
하지만 사용처가 한정적이고 개발 과정이 귀찮은 부분이 있어서 그 외의 목적으로는 사용하지는 않을 것 같습니다.

2023-07-30 13:58 UTC, bandal-reviewer approved these changes
고생많으셨습니다.

참고로 TDD의 경우 Green 단계 즉. 죄악을 저지르는 단계는 TDD가 완전히 체화가 되었다면 생략하셔도 좋습니다. ㅎㅎ

2023-07-30 13:58 UTC, merged